extends: default

ignore: |
  /node_modules/

rules:
  line-length: 
    max: 120
  brackets: enable
  colons: enable
  commas: enable
  comments:
    level: warning
  comments-indentation:
    level: warning
  document-end: enable
  document-start: enable
  empty-lines: enable
  empty-values: enable
  hyphens: enable
  indentation: enable
  key-duplicates: enable
  key-ordering: enable
  new-line-at-end-of-file: enable
  new-lines: enable
  octal-values: enable
  quoted-strings: enable
  trailing-spaces: enable
  truthy: enable
