version: "1.0"
stages:
  - "clone"
  - "build"
  - "test"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "rusliktest/git-actions"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  build:
    title: "Building Docker image"
    type: "build"
    image_name: "rusliktest/git-actions"
    working_directory: "${{clone}}"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    # If you have a Dockerfile in the repo you can use
    # dockerfile: 'Dockerfile'
    dockerfile:
      content: "FROM python:3-alpine\n          RUN apk add --no-cache bash gcc musl-dev\n          RUN pip install 'yamllint>=1.25.0'\n          RUN rm -rf ~/.cache/pip\n          ADD entrypoint.sh /entrypoint.sh\n          ENTRYPOINT ['/entrypoint.sh']"
    stage: "build"

  test:
    title: "Running test"
    type: "freestyle" # Run any command
    image: "ubuntu:latest" # The image in which command will be executed
    working_directory: "${{clone}}" # Running command where code cloned
    commands:
      - "chmod +x entrypoint.sh"
      - "bash entrypoint.sh"
    stage: "test"

