version: "1.0"
stages:
  - "clone"
  - "build"
  - "test"

steps:
  yaml-lint:
  title: YAML Lint
  description: Validate YAML syntax
  type: github-action-executor
  arguments:
    url: 'https://github.com/marketplace/actions/yaml-lint'
    envs:
      - INPUT_FILE_OR_DIR: ./*.yaml  #./**/*val*.yaml
      - INPUT_CONFIG_FILE: .yamllint.yml
      - INPUT_CONFIG_DATA: "{extends: default}"
    registry: dockerhub
    registry_repo: codefreshplugins


